/// @file
/// @brief Pluggable per-turn context compaction strategy.
///
/// Mirrors the Hermes Agent agent/context_engine.py + context_compressor.py
/// pattern: a pluggable abstraction that inspects a session's message
/// history and returns a *plan* describing which range to compact. The
/// summary itself is generated by the caller (typically using a cheap
/// auxiliary model) so this header stays deterministic and unit-testable.
///
/// The default WindowedContextEngine implements the head/tail strategy
/// observed across Hermes and OpenClaw: preserve the most recent N turns
/// verbatim (tool results stay actionable), preserve the first M turns
/// verbatim (system prompt + early user context), and earmark the middle
/// for summarisation. Fires only when estimated tokens cross a configurable
/// fraction of the model's context window.
#pragma once

#include <cstddef>
#include <memory>
#include <string>
#include <vector>

#include "agent_session.hpp"

namespace euxis::runtime {

/// @brief Compaction strategy decision returned by an IContextEngine.
///
/// An "empty" plan (all-zero indices, compact_end == compact_start) means
/// "no compaction needed this turn". Callers must check `is_empty()`
/// before acting on the plan.
struct CompactionPlan {
    /// @brief Preserve messages[0 .. keep_head) verbatim.
    std::size_t keep_head{0};
    /// @brief Preserve messages[size - keep_tail .. size) verbatim.
    std::size_t keep_tail{0};
    /// @brief First index of the range to summarise (inclusive).
    std::size_t compact_start{0};
    /// @brief Past-the-end index of the range to summarise (exclusive).
    std::size_t compact_end{0};
    /// @brief Role for the synthetic summary message.
    std::string summary_role{"system"};

    /// @brief True when no compaction is recommended.
    [[nodiscard]] auto is_empty() const noexcept -> bool {
        return compact_end <= compact_start;
    }

    /// @brief Number of messages this plan will replace with one summary.
    [[nodiscard]] auto compact_count() const noexcept -> std::size_t {
        return compact_end - compact_start;
    }
};

/// @brief Pluggable per-turn context compaction strategy.
///
/// Implementations are pure: given the current message vector, an
/// estimated total token count, and the context-window size of the
/// model being targeted, return a CompactionPlan. No side effects, no
/// I/O, no model calls — those happen in the loop that consumes the
/// plan.
class IContextEngine {
public:
    virtual ~IContextEngine() = default;

    /// @brief Plan a compaction for the next model call.
    /// @return An empty plan if no compaction is needed, otherwise the
    ///         range to compact and head/tail boundaries to preserve.
    [[nodiscard]] virtual auto plan(
        const std::vector<ConversationMessage>& messages,
        std::size_t estimated_tokens,
        std::size_t context_window) const -> CompactionPlan = 0;
};

/// @brief Default head/tail strategy.
///
/// Preserves the first `keep_head_messages` and last `keep_tail_messages`
/// verbatim and earmarks the middle for summarisation. Triggers when
/// estimated_tokens / context_window >= trigger_ratio.
///
/// Defaults are tuned to match Hermes:
///   - keep_head_messages = 4 (system + 3 turns)
///   - keep_tail_messages = 6 (latest 3 user/assistant pairs)
///   - trigger_ratio      = 0.75
class WindowedContextEngine final : public IContextEngine {
public:
    struct Config {
        std::size_t keep_head_messages{4};
        std::size_t keep_tail_messages{6};
        double      trigger_ratio{0.75};
    };

    WindowedContextEngine() noexcept;
    explicit WindowedContextEngine(Config cfg) noexcept;

    [[nodiscard]] auto plan(
        const std::vector<ConversationMessage>& messages,
        std::size_t estimated_tokens,
        std::size_t context_window) const -> CompactionPlan override;

    [[nodiscard]] auto config() const noexcept -> const Config& { return cfg_; }

private:
    Config cfg_;
};

/// @brief Rough token estimate for a message vector.
///
/// Heuristic: 4 bytes ≈ 1 token (the long-standing OpenAI-style rule of
/// thumb). Counts `content` bytes only; metadata fields (agent_id, model,
/// timestamp, decision_trace_hash) are ignored as their cost is fixed
/// per message regardless of conversation depth.
///
/// Replace with a real tokeniser (tiktoken-style) when a target model
/// is known; the heuristic is good enough for triggering compaction.
[[nodiscard]] auto estimate_tokens(
    const std::vector<ConversationMessage>& messages) noexcept -> std::size_t;

} // namespace euxis::runtime
