[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "euxis"
version = "0.0.1"
authors = [
    { name = "Sebastian Rousseau", email = "sebastian.rousseau@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
description = "An open-source attempt to make GPT-4 autonomous"

[project.urls]
"Homepage" = "https://github.com/sebastienrousseau/euxis"
"Bug Tracker" = "https://github.com/sebastienrousseau/euxis"

[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
packages = ["euxis"]
extend-exclude = '.+/(dist|.venv|venv|build)/.+'


[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip = '''
    .tox
    __pycache__
    *.pyc
    .env
    venv*/*
    .venv/*
    reports/*
    dist/*

'''

[tool.pytest.ini_options]
markers = ["requires_openai_api_key", "requires_huggingface_api_key"]
