#include <gtest/gtest.h>

#include "euxis/sbom/cyclonedx.hpp"
#include "euxis/sbom/purl.hpp"

#include <nlohmann/json.hpp>

namespace euxis::sbom {
namespace {

SbomDocument minimal_doc() {
    SbomDocument doc;
    doc.serial_number = "urn:uuid:00000000-0000-4000-8000-000000000000";
    doc.tools.push_back({"euxis.co", "euxis-cli", "0.1.0-test"});
    Component root;
    root.bom_ref = "pkg:euxis/self@0.1.0";
    root.name    = "euxis-self";
    root.version = "0.1.0";
    root.type    = ComponentType::Application;
    doc.root = root;

    Component dep;
    dep.bom_ref = "pkg:cargo/serde@1.0.197";
    dep.purl    = Purl::build(PurlType::Cargo, "serde", "1.0.197").to_string();
    dep.name    = "serde";
    dep.version = "1.0.197";
    dep.licenses.push_back({"MIT", std::nullopt});
    dep.hashes.push_back({HashAlgorithm::Sha256, std::string(64, 'a')});
    dep.properties["euxis:direct"] = "true";
    doc.components.push_back(dep);

    Component dep2;
    dep2.bom_ref = "pkg:npm/lodash@4.17.21";
    dep2.purl    = "pkg:npm/lodash@4.17.21";
    dep2.name    = "lodash";
    dep2.version = "4.17.21";
    dep2.type    = ComponentType::Library;
    doc.components.push_back(dep2);

    doc.dependencies.push_back({"pkg:euxis/self@0.1.0",
                                {"pkg:cargo/serde@1.0.197", "pkg:npm/lodash@4.17.21"}});
    return doc;
}

TEST(CycloneDX16, EmitsSpecVersionAndBomFormat) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    EXPECT_EQ(json["bomFormat"],   "CycloneDX");
    EXPECT_EQ(json["specVersion"], "1.6");
    EXPECT_EQ(json["version"],     1);
}

TEST(CycloneDX16, SerialNumberRetained) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    EXPECT_EQ(json["serialNumber"], "urn:uuid:00000000-0000-4000-8000-000000000000");
}

TEST(CycloneDX16, SerialNumberAutoGeneratedWhenEmpty) {
    SbomDocument doc;
    auto json = to_cyclonedx_1_6(doc);
    auto sn = json["serialNumber"].get<std::string>();
    EXPECT_TRUE(sn.starts_with("urn:uuid:"));
}

TEST(CycloneDX16, MetadataIncludesTimestampAndTools) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    ASSERT_TRUE(json["metadata"].contains("timestamp"));
    ASSERT_TRUE(json["metadata"]["tools"].contains("components"));
    EXPECT_EQ(json["metadata"]["tools"]["components"][0]["name"], "euxis-cli");
}

TEST(CycloneDX16, RootComponentInMetadata) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    ASSERT_TRUE(json["metadata"].contains("component"));
    EXPECT_EQ(json["metadata"]["component"]["name"], "euxis-self");
    EXPECT_EQ(json["metadata"]["component"]["type"], "application");
}

TEST(CycloneDX16, ComponentsArrayPopulated) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    ASSERT_TRUE(json.contains("components"));
    EXPECT_EQ(json["components"].size(), 2U);
    EXPECT_EQ(json["components"][0]["name"], "serde");
    EXPECT_EQ(json["components"][0]["version"], "1.0.197");
    EXPECT_EQ(json["components"][0]["purl"], "pkg:cargo/serde@1.0.197");
}

TEST(CycloneDX16, LicenseEmittedAsExpression) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    EXPECT_EQ(json["components"][0]["licenses"][0]["expression"], "MIT");
}

TEST(CycloneDX16, HashEmittedWithHyphenatedAlg) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    EXPECT_EQ(json["components"][0]["hashes"][0]["alg"], "SHA-256");
    EXPECT_EQ(json["components"][0]["hashes"][0]["content"].get<std::string>().size(), 64U);
}

TEST(CycloneDX16, PropertiesEmittedAsKeyValueArray) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    ASSERT_TRUE(json["components"][0].contains("properties"));
    EXPECT_EQ(json["components"][0]["properties"][0]["name"], "euxis:direct");
    EXPECT_EQ(json["components"][0]["properties"][0]["value"], "true");
}

TEST(CycloneDX16, DependencyGraphEmitted) {
    auto json = to_cyclonedx_1_6(minimal_doc());
    ASSERT_TRUE(json.contains("dependencies"));
    EXPECT_EQ(json["dependencies"][0]["ref"], "pkg:euxis/self@0.1.0");
    EXPECT_EQ(json["dependencies"][0]["dependsOn"].size(), 2U);
}

TEST(CycloneDX16, EmptyDocStillValidShape) {
    SbomDocument doc;
    auto json = to_cyclonedx_1_6(doc);
    EXPECT_EQ(json["bomFormat"], "CycloneDX");
    EXPECT_EQ(json["specVersion"], "1.6");
    EXPECT_TRUE(json["components"].is_array());
    EXPECT_FALSE(json.contains("dependencies"));
}

} // namespace
} // namespace euxis::sbom
