/// @file
/// @brief Canonical Finding type for the euxis scanner.
///
/// Every code path that produces a finding — taint engine, secret
/// detector, dependency resolver, slopsquatting guard, LLM autotriage —
/// emits this struct. Downstream emitters (SARIF, GitHub Annotations,
/// GitLab Code Quality, JUnit, Markdown, evidence pack) consume it.
#pragma once

#include <chrono>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace euxis::security {

/// Severity totally ordered: Critical > High > Medium > Low > Info > None.
enum class Severity : std::uint8_t {
    None     = 0,
    Info     = 1,
    Low      = 2,
    Medium   = 3,
    High     = 4,
    Critical = 5,
};

/// Confidence the finding is a true positive. Default is Probable for
/// pattern-match rules; Verified is reserved for findings whose
/// exploit path has been demonstrated (symex witness, ensemble quorum,
/// reachability proof).
enum class Confidence : std::uint8_t {
    Unknown    = 0,
    Possible   = 1,
    Probable   = 2,
    Verified   = 3,
};

/// Where the rule that produced this finding came from. Affects how
/// the finding is signed in the evidence pack.
enum class RuleSource : std::uint8_t {
    EuxisCore         = 0, ///< First-party euxis rule pack.
    OpenGrep          = 1, ///< Ingested from an OpenGrep YAML pack.
    UserDefined       = 2, ///< From .euxis.yaml rules.custom.
    LlmInferred       = 3, ///< Generated by the LLM mining stage (AdaTaint).
    DependencyScanner = 4, ///< From the SCA pipeline.
    SecretDetector    = 5,
    SlopsquattingGuard = 6,
};

/// CWE reference. Empty cwe_id means the finding has no CWE mapping.
struct CweRef {
    std::string id;          ///< e.g. "CWE-79"
    std::string short_name;  ///< e.g. "Cross-Site Scripting"
    bool in_top_25_2025{false};
    int top_25_rank{0};      ///< 0 = not ranked
};

/// OWASP Top 10:2025 reference. Use OwaspCategory::A03_SupplyChain etc.
enum class OwaspCategory : std::uint8_t {
    None = 0,
    A01_BrokenAccessControl,
    A02_CryptographicFailures,
    A03_SupplyChainFailures,
    A04_InsecureDesign,
    A05_SecurityMisconfiguration,
    A06_VulnerableComponents,
    A07_AuthenticationFailures,
    A08_DataIntegrityFailures,
    A09_LoggingMonitoringFailures,
    A10_MishandlingExceptionalConditions,
};

/// Quantum-vulnerable cryptographic primitive flag (CNSA 2.0).
enum class QuantumDeprecation : std::uint8_t {
    None              = 0,
    Rsa               = 1, ///< Any key size; CNSA 2.0 deprecation 2030.
    Ecdsa             = 2,
    Ecdh              = 3,
    DhFiniteField     = 4,
    Sha1InSignature   = 5,
    Md5InSignature    = 6,
    NonHybridKemMlKem = 7, ///< Transitional warn.
    NonHybridSigMlDsa = 8,
};

/// Location within a source file. Lines/columns are 1-based.
struct SourceLocation {
    std::string path;
    int start_line{0};
    int start_column{0};
    int end_line{0};
    int end_column{0};
    std::string snippet;   ///< Optional; redacted if size > 4 KiB.
};

/// Suggested fix. Generated only when a deterministic codemod exists
/// or the autotriage ensemble has produced a verified patch.
struct FixSuggestion {
    std::string description;
    std::string replacement_text;
    SourceLocation replacement_range;
    bool deterministic{false};  ///< True for Pixee-style codemods.
};

/// A single finding. Produced by every analysis pipeline; consumed by
/// every emitter. Stable in serialised form across releases — adding
/// new fields is always optional, never required.
struct Finding {
    /// Stable, deterministic id derived from BLAKE2b-128 of
    /// (rule_id, normalised path, AST-shape hash). Survives line
    /// moves and whitespace churn. Used for baseline-file matching.
    std::string stable_fingerprint;

    /// Rule identifier, namespaced. e.g. "euxis/cwe-79", "opengrep/rust.unsafe-deref".
    std::string rule_id;

    /// One-sentence human-readable description.
    std::string message;

    Severity severity{Severity::Medium};
    Confidence confidence{Confidence::Probable};
    RuleSource source{RuleSource::EuxisCore};

    /// Primary source location. May be empty for cross-file findings,
    /// in which case `related_locations` is consulted.
    SourceLocation primary_location;
    std::vector<SourceLocation> related_locations;

    std::optional<CweRef> cwe;
    OwaspCategory owasp{OwaspCategory::None};
    QuantumDeprecation quantum{QuantumDeprecation::None};

    /// Compliance taxa the rule maps to. Free-form strings so the set
    /// stays open as new frameworks land (CRA, DORA, FedRAMP, etc.).
    std::vector<std::string> compliance_taxa;

    std::vector<FixSuggestion> fixes;

    /// Optional ensemble vote record. Populated when CodeX-Verify
    /// triage runs. Quorum semantics live in libs/runtime/ensemble.
    struct EnsembleVote {
        std::string provider;     ///< e.g. "claude-opus-4-7"
        bool true_positive{false};
        float confidence{0.0F};
    };
    std::vector<EnsembleVote> ensemble_votes;

    /// When the finding was produced. Used in the evidence pack
    /// timestamp section.
    std::chrono::system_clock::time_point produced_at{
        std::chrono::system_clock::now()};
};

/// Severity → SARIF level string. SARIF accepts {none, note, warning, error}.
[[nodiscard]] constexpr auto sarif_level(Severity s) noexcept -> const char* {
    switch (s) {
        case Severity::Critical:
        case Severity::High:     return "error";
        case Severity::Medium:   return "warning";
        case Severity::Low:
        case Severity::Info:     return "note";
        case Severity::None:     return "none";
    }
    return "warning";
}

/// Severity → CLI symbol (used in TUI summary output).
[[nodiscard]] constexpr auto severity_label(Severity s) noexcept -> const char* {
    switch (s) {
        case Severity::Critical: return "CRITICAL";
        case Severity::High:     return "HIGH";
        case Severity::Medium:   return "MEDIUM";
        case Severity::Low:      return "LOW";
        case Severity::Info:     return "INFO";
        case Severity::None:     return "NONE";
    }
    return "UNKNOWN";
}

/// OWASP category → SARIF-property string.
[[nodiscard]] auto owasp_id(OwaspCategory c) noexcept -> const char*;

/// OWASP category → human-readable label.
[[nodiscard]] auto owasp_label(OwaspCategory c) noexcept -> const char*;

/// QuantumDeprecation → human-readable label for evidence-pack text.
[[nodiscard]] auto quantum_label(QuantumDeprecation q) noexcept -> const char*;

/// Parse a `Severity` from a CLI-style string. Returns Severity::None
/// on no match so the caller can detect bad input.
[[nodiscard]] auto parse_severity(const std::string& s) noexcept -> Severity;

} // namespace euxis::security
