/// @file
/// @brief Integration tests for `cmd_sbom` — the implementation
///        behind `euxis sbom`. Drives directory walk + lockfile
///        parsing (libs/sca) + format emission (libs/sbom) so the
///        126 uncovered lines that the 2026-06-22 gcovr baseline
///        flagged at 0% become live.

#include <gtest/gtest.h>

#include "euxis/cli/cmd/sbom.hpp"
#include "euxis/cli/command.hpp"
#include "euxis/cli/exit_codes.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <sstream>
#include <string>
#include <unistd.h>
#include <vector>

#include <nlohmann/json.hpp>

// NOLINTBEGIN(cert-err33-c) — test scratch I/O intentionally discards
// return values; tests can blanket-disable per
// docs/development/clang-tidy-policy.md.

namespace euxis::cli::cmd {
namespace {

namespace fs = std::filesystem;

class SbomCmdTest : public ::testing::Test {
protected:
    fs::path tmpdir;
    fs::path cwd_before;
    Context  ctx;

    void SetUp() override {
        tmpdir = fs::temp_directory_path() /
                 ("euxis_test_sbom_" + std::to_string(::getpid()) +
                  "_" + std::to_string(reinterpret_cast<std::uintptr_t>(this)));
        fs::create_directories(tmpdir);
        // Default-output filenames are written to the *current* working
        // directory, so chdir into tmpdir to keep test output sandboxed.
        cwd_before = fs::current_path();
        fs::current_path(tmpdir);
        ctx.euxis_home = tmpdir.string();
        ctx.data_dir   = (tmpdir / "data").string();
    }

    void TearDown() override {
        fs::current_path(cwd_before);
        std::error_code ec;
        fs::remove_all(tmpdir, ec);
    }

    std::string capture_fd(int target_fd, std::function<int()> fn) {
        auto* tmp = std::tmpfile();
        if (tmp == nullptr) return {};
        int old_fd = ::dup(target_fd);
        ::dup2(::fileno(tmp), target_fd);
        fn();
        if (target_fd == STDOUT_FILENO) ::fflush(stdout);
        if (target_fd == STDERR_FILENO) ::fflush(stderr);
        ::dup2(old_fd, target_fd);
        ::close(old_fd);
        std::rewind(tmp);
        std::string out;
        char buf[4096];
        size_t n = 0;
        while ((n = std::fread(buf, 1, sizeof(buf), tmp)) > 0) {
            out.append(buf, n);
        }
        std::fclose(tmp);
        return out;
    }
    std::string capture_stdout(std::function<int()> fn) {
        return capture_fd(STDOUT_FILENO, std::move(fn));
    }
    std::string capture_cerr(std::function<int()> fn) {
        return capture_fd(STDERR_FILENO, std::move(fn));
    }

    // Drop a minimal Cargo.lock the libs/sca parser recognises.
    void write_cargo_lock() {
        std::ofstream{tmpdir / "Cargo.lock"} <<
            "# This file is automatically @generated by Cargo.\n"
            "version = 3\n"
            "\n"
            "[[package]]\n"
            "name = \"serde\"\n"
            "version = \"1.0.197\"\n"
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n"
            "checksum = \"3fb1c7a9d4d9ad9d4b0c84d2f9e2b3a4f5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0\"\n"
            "\n"
            "[[package]]\n"
            "name = \"euxis-fixture\"\n"
            "version = \"0.1.0\"\n"
            "dependencies = [\n"
            " \"serde\",\n"
            "]\n";
    }
};

// ---------------------------------------------------------------------------
// Help + arg-parser errors
// ---------------------------------------------------------------------------

TEST_F(SbomCmdTest, HelpFlagPrintsHelp) {
    auto out = capture_stdout([&]() {
        return cmd_sbom(ctx, {"--help"});
    });
    EXPECT_NE(out.find("Usage: euxis sbom"), std::string::npos);
}

TEST_F(SbomCmdTest, ShortHelpFlagAlsoPrintsHelp) {
    auto out = capture_stdout([&]() {
        return cmd_sbom(ctx, {"-h"});
    });
    EXPECT_NE(out.find("Usage: euxis sbom"), std::string::npos);
}

TEST_F(SbomCmdTest, UnknownFlagIsInfraError) {
    auto err = capture_cerr([&]() {
        return cmd_sbom(ctx, {"--not-a-real-flag"});
    });
    EXPECT_NE(err.find("Unknown flag"), std::string::npos);
}

TEST_F(SbomCmdTest, InvalidFormatIsInfraError) {
    auto err = capture_cerr([&]() {
        return cmd_sbom(ctx, {"--format=swid"});
    });
    EXPECT_NE(err.find("--format"), std::string::npos);
}

TEST_F(SbomCmdTest, ExtraPositionalIsInfraError) {
    auto err = capture_cerr([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "second-positional"});
    });
    EXPECT_NE(err.find("Unexpected positional"), std::string::npos);
}

// ---------------------------------------------------------------------------
// Format dispatch — happy paths
// ---------------------------------------------------------------------------

TEST_F(SbomCmdTest, DefaultEmitsCycloneDx) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string()});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.cdx.json"));
}

TEST_F(SbomCmdTest, ExplicitCycloneDxFormat) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=cyclonedx"});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.cdx.json"));
}

TEST_F(SbomCmdTest, CycloneDxVersionedAlias) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=cyclonedx-1.6"});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.cdx.json"));
}

TEST_F(SbomCmdTest, SpdxFormat) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=spdx"});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.spdx.json"));
}

TEST_F(SbomCmdTest, SpdxVersionedAlias) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=spdx-3.0.1"});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.spdx.json"));
}

TEST_F(SbomCmdTest, BothFormatEmitsTwoFiles) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=both"});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.cdx.json"));
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.spdx.json"));
}

TEST_F(SbomCmdTest, OpenVexFormat) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=openvex"});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-vex.openvex.json"));
}

// ---------------------------------------------------------------------------
// Output + pretty options
// ---------------------------------------------------------------------------

TEST_F(SbomCmdTest, ExplicitOutputPath) {
    write_cargo_lock();
    auto out_path = tmpdir / "custom.cdx.json";
    capture_stdout([&]() {
        return cmd_sbom(ctx, {
            tmpdir.string(),
            "--output=" + out_path.string(),
        });
    });
    EXPECT_TRUE(fs::exists(out_path));
}

TEST_F(SbomCmdTest, BothFormatTreatsOutputAsBasename) {
    write_cargo_lock();
    auto base = tmpdir / "mybase";
    capture_stdout([&]() {
        return cmd_sbom(ctx, {
            tmpdir.string(),
            "--format=both",
            "--output=" + base.string(),
        });
    });
    EXPECT_TRUE(fs::exists(tmpdir / "mybase.cdx.json"));
    EXPECT_TRUE(fs::exists(tmpdir / "mybase.spdx.json"));
}

TEST_F(SbomCmdTest, NoPrettyEmitsCompactJson) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--no-pretty"});
    });
    auto out = tmpdir / "euxis-sbom.cdx.json";
    ASSERT_TRUE(fs::exists(out));
    // Compact JSON has no newlines between fields.
    std::ifstream f(out);
    std::stringstream ss; ss << f.rdbuf();
    auto body = ss.str();
    // Single trailing newline added by write_json. Any other \n
    // would indicate pretty-printing.
    auto newlines = std::count(body.begin(), body.end(), '\n');
    EXPECT_LE(newlines, 1);
}

TEST_F(SbomCmdTest, PrettyFlagIsTheDefault) {
    write_cargo_lock();
    // No --pretty: should match --pretty=true.
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--pretty"});
    });
    auto out = tmpdir / "euxis-sbom.cdx.json";
    ASSERT_TRUE(fs::exists(out));
    std::ifstream f(out);
    std::stringstream ss; ss << f.rdbuf();
    auto body = ss.str();
    // Pretty JSON has multiple newlines.
    auto newlines = std::count(body.begin(), body.end(), '\n');
    EXPECT_GT(newlines, 1);
}

// ---------------------------------------------------------------------------
// Content checks — emitted JSON includes parsed components
// ---------------------------------------------------------------------------

TEST_F(SbomCmdTest, CycloneDxIncludesParsedComponent) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string()});
    });
    std::ifstream f(tmpdir / "euxis-sbom.cdx.json");
    nlohmann::json j = nlohmann::json::parse(f);
    EXPECT_EQ(j["bomFormat"], "CycloneDX");
    EXPECT_EQ(j["specVersion"], "1.6");
    ASSERT_TRUE(j["components"].is_array());
    // Cargo.lock fixture defines two packages.
    EXPECT_GE(j["components"].size(), 1u);
}

TEST_F(SbomCmdTest, SpdxEmitsValidJsonLd) {
    write_cargo_lock();
    capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string(), "--format=spdx"});
    });
    std::ifstream f(tmpdir / "euxis-sbom.spdx.json");
    nlohmann::json j = nlohmann::json::parse(f);
    // SPDX 3.0.1 ships as JSON-LD: @context + @graph at the top level.
    ASSERT_TRUE(j.contains("@context"));
    ASSERT_TRUE(j.contains("@graph"));
    ASSERT_TRUE(j["@graph"].is_array());
    EXPECT_FALSE(j["@graph"].empty());
}

TEST_F(SbomCmdTest, EmptyTargetSucceedsWithZeroComponents) {
    // No lockfiles → scan succeeds with empty manifests vector.
    auto out = capture_stdout([&]() {
        return cmd_sbom(ctx, {tmpdir.string()});
    });
    EXPECT_TRUE(fs::exists(tmpdir / "euxis-sbom.cdx.json"));
    EXPECT_NE(out.find("0 component"), std::string::npos);
}

} // namespace
} // namespace euxis::cli::cmd

// NOLINTEND(cert-err33-c)
