set(lupdate_project_file "/home/seb/.euxis/euxis-cpp/CMakeLists.txt")
set(lupdate_translations "/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_en.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_fr.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_es.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_de.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_pt.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_zh.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_ja.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_ko.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_ru.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_it.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_ar.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_he.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_hi.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_nl.ts;/home/seb/.euxis/euxis-cpp/euxis-etx/translations/euxis_etx_id.ts")
set(lupdate_include_paths "")
set(lupdate_sources "")
set(lupdate_subproject_count 36)

set(lupdate_subproject1_source_dir "/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src")
set(lupdate_subproject1_include_paths "")
set(lupdate_subproject1_sources "")
set(lupdate_subproject1_excluded "")
set(lupdate_subproject1_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-build/httplib_autogen")

set(lupdate_subproject2_source_dir "/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src")
set(lupdate_subproject2_include_paths "/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/")
set(lupdate_subproject2_sources "ixwebsocket/IXBench.cpp;ixwebsocket/IXCancellationRequest.cpp;ixwebsocket/IXConnectionState.cpp;ixwebsocket/IXDNSLookup.cpp;ixwebsocket/IXExponentialBackoff.cpp;ixwebsocket/IXHttp.cpp;ixwebsocket/IXHttpClient.cpp;ixwebsocket/IXHttpServer.cpp;ixwebsocket/IXNetSystem.cpp;ixwebsocket/IXSelectInterrupt.cpp;ixwebsocket/IXSelectInterruptFactory.cpp;ixwebsocket/IXSocket.cpp;ixwebsocket/IXSocketConnect.cpp;ixwebsocket/IXSocketFactory.cpp;ixwebsocket/IXSocketServer.cpp;ixwebsocket/IXSocketTLSOptions.cpp;ixwebsocket/IXUdpSocket.cpp;ixwebsocket/IXUrlParser.cpp;ixwebsocket/IXUserAgent.cpp;ixwebsocket/IXWebSocket.cpp;ixwebsocket/IXWebSocketCloseConstants.cpp;ixwebsocket/IXWebSocketHandshake.cpp;ixwebsocket/IXWebSocketHttpHeaders.cpp;ixwebsocket/IXWebSocketPerMessageDeflate.cpp;ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp;ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp;ixwebsocket/IXWebSocketServer.cpp;ixwebsocket/IXWebSocketTransport.cpp;ixwebsocket/IXSelectInterruptPipe.cpp;ixwebsocket/IXSelectInterruptPipe.h;ixwebsocket/linux/IXSetThreadName_linux.cpp;ixwebsocket/IXBench.h;ixwebsocket/IXCancellationRequest.h;ixwebsocket/IXConnectionInfo.h;ixwebsocket/IXConnectionState.h;ixwebsocket/IXDNSLookup.h;ixwebsocket/IXExponentialBackoff.h;ixwebsocket/IXHttp.h;ixwebsocket/IXHttpClient.h;ixwebsocket/IXHttpServer.h;ixwebsocket/IXNetSystem.h;ixwebsocket/IXProgressCallback.h;ixwebsocket/IXSelectInterrupt.h;ixwebsocket/IXSelectInterruptFactory.h;ixwebsocket/IXSetThreadName.h;ixwebsocket/IXSocket.h;ixwebsocket/IXSocketConnect.h;ixwebsocket/IXSocketFactory.h;ixwebsocket/IXSocketServer.h;ixwebsocket/IXSocketTLSOptions.h;ixwebsocket/IXUdpSocket.h;ixwebsocket/IXUrlParser.h;ixwebsocket/IXUtf8Validator.h;ixwebsocket/IXUserAgent.h;ixwebsocket/IXWebSocket.h;ixwebsocket/IXWebSocketCloseConstants.h;ixwebsocket/IXWebSocketCloseInfo.h;ixwebsocket/IXWebSocketErrorInfo.h;ixwebsocket/IXWebSocketHandshake.h;ixwebsocket/IXWebSocketHandshakeKeyGen.h;ixwebsocket/IXWebSocketHttpHeaders.h;ixwebsocket/IXWebSocketInitResult.h;ixwebsocket/IXWebSocketMessage.h;ixwebsocket/IXWebSocketMessageType.h;ixwebsocket/IXWebSocketOpenInfo.h;ixwebsocket/IXWebSocketPerMessageDeflate.h;ixwebsocket/IXWebSocketPerMessageDeflateCodec.h;ixwebsocket/IXWebSocketPerMessageDeflateOptions.h;ixwebsocket/IXWebSocketSendInfo.h;ixwebsocket/IXWebSocketServer.h;ixwebsocket/IXWebSocketTransport.h;ixwebsocket/IXWebSocketVersion.h")
set(lupdate_subproject2_excluded "")
set(lupdate_subproject2_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-build/ixwebsocket_autogen")

set(lupdate_subproject3_source_dir "/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp")
set(lupdate_subproject3_include_paths "/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject3_sources "src/aes_gcm.cpp;src/key_derivation.cpp;src/ed25519.cpp")
set(lupdate_subproject3_excluded "")
set(lupdate_subproject3_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-crypto-cpp/euxis-crypto-cpp_autogen")

set(lupdate_subproject4_source_dir "/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp")
set(lupdate_subproject4_include_paths "/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject4_sources "tests/test_aes_gcm.cpp;tests/test_aes_gcm_aad.cpp;tests/test_key_derivation.cpp;tests/test_ed25519.cpp")
set(lupdate_subproject4_excluded "")
set(lupdate_subproject4_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-crypto-cpp/euxis-crypto-cpp_tests_autogen")

set(lupdate_subproject5_source_dir "/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp")
set(lupdate_subproject5_include_paths "/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject5_sources "src/skill.cpp;src/policy.cpp;src/importer.cpp;src/parser.cpp;src/verification.cpp;src/static_analysis.cpp;src/admission.cpp;src/reputation.cpp;src/provenance.cpp;src/audit.cpp;src/executor.cpp;src/platform_linux.cpp")
set(lupdate_subproject5_excluded "")
set(lupdate_subproject5_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-bridge-cpp/euxis-bridge-cpp_autogen")

set(lupdate_subproject6_source_dir "/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp")
set(lupdate_subproject6_include_paths "/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject6_sources "tests/test_skill.cpp;tests/test_policy.cpp;tests/test_importer.cpp;tests/test_parser.cpp;tests/test_verification.cpp;tests/test_static_analysis.cpp;tests/test_admission.cpp;tests/test_reputation.cpp;tests/test_provenance.cpp;tests/test_audit.cpp;tests/test_executor.cpp;tests/test_platform.cpp")
set(lupdate_subproject6_excluded "")
set(lupdate_subproject6_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-bridge-cpp/euxis-bridge-cpp_tests_autogen")

set(lupdate_subproject7_source_dir "/home/seb/.euxis/euxis-cpp/euxis-memory-cpp")
set(lupdate_subproject7_include_paths "/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject7_sources "src/store.cpp;src/entry.cpp")
set(lupdate_subproject7_excluded "")
set(lupdate_subproject7_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-memory-cpp/euxis-memory-cpp_autogen")

set(lupdate_subproject8_source_dir "/home/seb/.euxis/euxis-cpp/euxis-memory-cpp")
set(lupdate_subproject8_include_paths "/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject8_sources "tests/test_store.cpp;tests/test_tier_isolation.cpp;tests/test_destroy_keys.cpp;tests/test_entry.cpp")
set(lupdate_subproject8_excluded "")
set(lupdate_subproject8_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-memory-cpp/euxis-memory-cpp_tests_autogen")

set(lupdate_subproject9_source_dir "/home/seb/.euxis/euxis-cpp/euxis-identity-cpp")
set(lupdate_subproject9_include_paths "/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject9_sources "src/did.cpp;src/credentials.cpp;src/attestation.cpp;src/registry.cpp;src/erc8004.cpp")
set(lupdate_subproject9_excluded "")
set(lupdate_subproject9_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-identity-cpp/euxis-identity-cpp_autogen")

set(lupdate_subproject10_source_dir "/home/seb/.euxis/euxis-cpp/euxis-identity-cpp")
set(lupdate_subproject10_include_paths "/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject10_sources "tests/test_did.cpp;tests/test_credentials.cpp;tests/test_attestation.cpp;tests/test_registry.cpp;tests/test_erc8004.cpp")
set(lupdate_subproject10_excluded "")
set(lupdate_subproject10_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-identity-cpp/euxis-identity-cpp_tests_autogen")

set(lupdate_subproject11_source_dir "/home/seb/.euxis/euxis-cpp/euxis-inference-cpp")
set(lupdate_subproject11_include_paths "/home/seb/.euxis/euxis-cpp/euxis-inference-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject11_sources "src/config.cpp;src/model_registry.cpp;src/quality_gate.cpp;src/llama_engine.cpp;src/ollama_engine.cpp")
set(lupdate_subproject11_excluded "")
set(lupdate_subproject11_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-inference-cpp/euxis-inference-cpp_autogen")

set(lupdate_subproject12_source_dir "/home/seb/.euxis/euxis-cpp/euxis-inference-cpp")
set(lupdate_subproject12_include_paths "/home/seb/.euxis/euxis-cpp/euxis-inference-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject12_sources "tests/test_config.cpp;tests/test_model_registry.cpp;tests/test_quality_gate.cpp;tests/test_llama_engine.cpp;tests/test_llama_engine_api.cpp;tests/test_ollama_engine.cpp;tests/test_ollama_engine_api.cpp")
set(lupdate_subproject12_excluded "")
set(lupdate_subproject12_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-inference-cpp/euxis-inference-cpp_tests_autogen")

set(lupdate_subproject13_source_dir "/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp")
set(lupdate_subproject13_include_paths "/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject13_sources "src/agent_card.cpp;src/task.cpp;src/message.cpp;src/server.cpp;src/http_transport.cpp")
set(lupdate_subproject13_excluded "")
set(lupdate_subproject13_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-a2a-cpp/euxis-a2a-cpp_autogen")

set(lupdate_subproject14_source_dir "/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp")
set(lupdate_subproject14_include_paths "/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject14_sources "tests/test_agent_card.cpp;tests/test_task.cpp;tests/test_message.cpp;tests/test_server.cpp;tests/test_http_transport.cpp")
set(lupdate_subproject14_excluded "")
set(lupdate_subproject14_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-a2a-cpp/euxis-a2a-cpp_tests_autogen")

set(lupdate_subproject15_source_dir "/home/seb/.euxis/euxis-cpp/euxis-security-cpp")
set(lupdate_subproject15_include_paths "/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/usr/include;/usr/include")
set(lupdate_subproject15_sources "src/policy.cpp;src/governance.cpp")
set(lupdate_subproject15_excluded "")
set(lupdate_subproject15_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-security-cpp/euxis-security-cpp_autogen")

set(lupdate_subproject16_source_dir "/home/seb/.euxis/euxis-cpp/euxis-security-cpp")
set(lupdate_subproject16_include_paths "/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject16_sources "tests/test_policy.cpp;tests/test_governance.cpp")
set(lupdate_subproject16_excluded "")
set(lupdate_subproject16_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-security-cpp/euxis-security-cpp_tests_autogen")

set(lupdate_subproject17_source_dir "/home/seb/.euxis/euxis-cpp/euxis-scripts-cpp")
set(lupdate_subproject17_include_paths "/home/seb/.euxis/euxis-cpp/euxis-scripts-cpp/include;/usr/include;/usr/include")
set(lupdate_subproject17_sources "src/tech_debt.cpp;src/docs_quality.cpp")
set(lupdate_subproject17_excluded "")
set(lupdate_subproject17_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-scripts-cpp/euxis-scripts-cpp_autogen")

set(lupdate_subproject18_source_dir "/home/seb/.euxis/euxis-cpp/euxis-scripts-cpp")
set(lupdate_subproject18_include_paths "/home/seb/.euxis/euxis-cpp/euxis-scripts-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject18_sources "tests/test_tech_debt.cpp;tests/test_docs_quality.cpp")
set(lupdate_subproject18_excluded "")
set(lupdate_subproject18_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-scripts-cpp/euxis-scripts-cpp_tests_autogen")

set(lupdate_subproject19_source_dir "/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp")
set(lupdate_subproject19_include_paths "/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject19_sources "src/validator.cpp;src/lifecycle.cpp;src/tool_registry.cpp;src/session_store.cpp;src/agent_session.cpp;src/manifesto.cpp;src/tool_manifest.cpp;src/interaction.cpp")
set(lupdate_subproject19_excluded "")
set(lupdate_subproject19_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-runtime-cpp/euxis-runtime-cpp_autogen")

set(lupdate_subproject20_source_dir "/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp")
set(lupdate_subproject20_include_paths "/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject20_sources "tests/test_validator.cpp;tests/test_lifecycle.cpp;tests/test_tool_registry.cpp;tests/test_session_store.cpp;tests/test_agent_session.cpp;tests/test_manifesto.cpp;tests/test_tool_manifest.cpp;tests/test_interaction.cpp")
set(lupdate_subproject20_excluded "")
set(lupdate_subproject20_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-runtime-cpp/euxis-runtime-cpp_tests_autogen")

set(lupdate_subproject21_source_dir "/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp")
set(lupdate_subproject21_include_paths "/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject21_sources "src/performance_collector.cpp;src/fast_collector.cpp;src/analyzer.cpp;src/evidence.cpp;src/validation_pipeline.cpp;src/mdspan_views.cpp")
set(lupdate_subproject21_excluded "")
set(lupdate_subproject21_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-metrics-cpp/euxis-metrics-cpp_autogen")

set(lupdate_subproject22_source_dir "/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp")
set(lupdate_subproject22_include_paths "/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject22_sources "tests/test_performance_collector.cpp;tests/test_fast_collector.cpp;tests/test_analyzer.cpp;tests/test_evidence.cpp;tests/test_validation_pipeline.cpp;tests/test_mdspan_views.cpp")
set(lupdate_subproject22_excluded "")
set(lupdate_subproject22_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-metrics-cpp/euxis-metrics-cpp_tests_autogen")

set(lupdate_subproject23_source_dir "/home/seb/.euxis/euxis-cpp/euxis-core-cpp")
set(lupdate_subproject23_include_paths "/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;")
set(lupdate_subproject23_sources "src/resilience.cpp;src/router.cpp;src/swarm.cpp;src/ws_client.cpp;src/topology_grid.cpp")
set(lupdate_subproject23_excluded "")
set(lupdate_subproject23_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-core-cpp/euxis-core-cpp_autogen")

set(lupdate_subproject24_source_dir "/home/seb/.euxis/euxis-cpp/euxis-core-cpp")
set(lupdate_subproject24_include_paths "/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/usr/include;/usr/include")
set(lupdate_subproject24_sources "tests/test_resilience.cpp;tests/test_router.cpp;tests/test_swarm.cpp;tests/test_ws_client.cpp;tests/test_topology_grid.cpp")
set(lupdate_subproject24_excluded "")
set(lupdate_subproject24_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-core-cpp/euxis-core-cpp_tests_autogen")

set(lupdate_subproject25_source_dir "/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp")
set(lupdate_subproject25_include_paths "/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject25_sources "src/slack.cpp;src/telegram.cpp;src/discord.cpp;src/whatsapp.cpp;src/registry.cpp")
set(lupdate_subproject25_excluded "")
set(lupdate_subproject25_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-adapters-cpp/euxis-adapters-cpp_autogen")

set(lupdate_subproject26_source_dir "/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp")
set(lupdate_subproject26_include_paths "/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject26_sources "tests/test_slack.cpp;tests/test_slack_api.cpp;tests/test_telegram.cpp;tests/test_telegram_api.cpp;tests/test_discord.cpp;tests/test_discord_api.cpp;tests/test_whatsapp.cpp;tests/test_whatsapp_api.cpp;tests/test_registry.cpp")
set(lupdate_subproject26_excluded "")
set(lupdate_subproject26_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-adapters-cpp/euxis-adapters-cpp_tests_autogen")

set(lupdate_subproject27_source_dir "/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp")
set(lupdate_subproject27_include_paths "/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject27_sources "src/config.cpp;src/state.cpp;src/auth.cpp;src/server.cpp;src/routes_health.cpp;src/routes_sessions.cpp;src/routes_webhooks.cpp;src/routes_admin.cpp;src/mcp.cpp;src/routes_mcp.cpp;src/websocket.cpp")
set(lupdate_subproject27_excluded "")
set(lupdate_subproject27_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-gateway-cpp/euxis-gateway-cpp_autogen")

set(lupdate_subproject28_source_dir "/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp")
set(lupdate_subproject28_include_paths "/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject28_sources "tests/test_config.cpp;tests/test_auth.cpp;tests/test_server.cpp;tests/test_routes.cpp;tests/test_mcp.cpp;tests/test_websocket.cpp;tests/test_state.cpp")
set(lupdate_subproject28_excluded "")
set(lupdate_subproject28_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-gateway-cpp/euxis-gateway-cpp_tests_autogen")

set(lupdate_subproject29_source_dir "/home/seb/.euxis/euxis-cpp/euxis-cli-cpp")
set(lupdate_subproject29_include_paths "/home/seb/.euxis/euxis-cpp/euxis-cli-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject29_sources "src/engine.cpp;src/omnigraph.cpp;src/terminal.cpp;src/term_caps.cpp;src/box.cpp;src/config_loader.cpp;src/pii_filter.cpp;src/process.cpp;src/session.cpp;src/registry_client.cpp;src/provider_router.cpp;src/provider_executor.cpp;src/auth_profile_store.cpp;src/cli_provider.cpp;src/cmd/system.cpp;src/cmd/fleet.cpp;src/cmd/knowledge.cpp;src/cmd/infra.cpp;src/cmd/dev.cpp;src/cmd/specialized.cpp")
set(lupdate_subproject29_excluded "")
set(lupdate_subproject29_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-cli-cpp/euxis-cli-lib_autogen")

set(lupdate_subproject30_source_dir "/home/seb/.euxis/euxis-cpp/euxis-cli-cpp")
set(lupdate_subproject30_include_paths "/home/seb/.euxis/euxis-cpp/euxis-cli-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject30_sources "src/main.cpp")
set(lupdate_subproject30_excluded "")
set(lupdate_subproject30_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-cli-cpp/euxis-cli_autogen")

set(lupdate_subproject31_source_dir "/home/seb/.euxis/euxis-cpp/euxis-cli-cpp")
set(lupdate_subproject31_include_paths "/home/seb/.euxis/euxis-cpp/euxis-cli-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject31_sources "tests/test_engine.cpp;tests/test_omnigraph.cpp;tests/test_terminal.cpp;tests/test_config_loader.cpp;tests/test_registry_client.cpp;tests/test_provider_router.cpp;tests/test_session.cpp;tests/test_pii_filter.cpp;tests/test_cmd_system.cpp;tests/test_cmd_fleet.cpp;tests/test_cmd_knowledge.cpp;tests/test_cmd_infra.cpp;tests/test_cmd_dev.cpp;tests/test_cmd_specialized.cpp;tests/test_auth_profile_store.cpp;tests/test_process.cpp;tests/test_provider_executor.cpp;tests/test_term_caps.cpp;tests/test_box.cpp;tests/test_cli_provider.cpp;tests/test_i18n.cpp")
set(lupdate_subproject31_excluded "")
set(lupdate_subproject31_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-cli-cpp/euxis-cli-cpp_tests_autogen")

set(lupdate_subproject32_source_dir "/home/seb/.euxis/euxis-cpp/euxis-bench-cpp")
set(lupdate_subproject32_include_paths "/home/seb/.euxis/euxis-cpp/euxis-bench-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-inference-cpp/include;;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp/include;")
set(lupdate_subproject32_sources "src/runner.cpp;src/reporter.cpp;src/security_bench.cpp;src/autonomy_bench.cpp;src/performance_bench.cpp;src/portability_bench.cpp;src/interop_bench.cpp;src/result_matrix.cpp")
set(lupdate_subproject32_excluded "")
set(lupdate_subproject32_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-bench-cpp/euxis-bench-cpp_autogen")

set(lupdate_subproject33_source_dir "/home/seb/.euxis/euxis-cpp/euxis-bench-cpp")
set(lupdate_subproject33_include_paths "/home/seb/.euxis/euxis-cpp/euxis-bench-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-inference-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp/include;/usr/include;/usr/include")
set(lupdate_subproject33_sources "tests/test_runner.cpp;tests/test_result_matrix.cpp;tests/test_bench_suites.cpp")
set(lupdate_subproject33_excluded "")
set(lupdate_subproject33_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-bench-cpp/euxis-bench-cpp_tests_autogen")

set(lupdate_subproject34_source_dir "/home/seb/.euxis/euxis-cpp/euxis-etx")
set(lupdate_subproject34_include_paths "/home/seb/.euxis/euxis-cpp/euxis-etx/include;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx_autogen/include;/usr/include/qt6/QtCore;/usr/include/qt6;/usr/lib/qt6/mkspecs/linux-g++;/usr/include/qt6;/usr/include/qt6/QtWidgets;/usr/include/qt6;/usr/include/qt6/QtGui;/usr/include/qt6;/usr/include;/usr/include;/usr/include;/usr/include/qt6/QtNetwork;/usr/include/qt6;/usr/include/qt6/QtSvgWidgets;/usr/include/qt6;/usr/include/qt6/QtSvg;/usr/include/qt6;/usr/include/qt6/QtConcurrent;/usr/include/qt6;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-inference-cpp/include;;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-cli-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/usr/include")
set(lupdate_subproject34_sources "/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx_autogen/mocs_compilation.cpp;include/euxis/etx/app.hpp;include/euxis/etx/theme.hpp;include/euxis/etx/registry.hpp;include/euxis/etx/chat_engine.hpp;include/euxis/etx/conversation_widget.hpp;include/euxis/etx/chat_input_widget.hpp;include/euxis/etx/ghost_text.hpp;include/euxis/etx/breadcrumb_widget.hpp;include/euxis/etx/bento_layout.hpp;include/euxis/etx/collapsible_section.hpp;include/euxis/etx/semantic_colors.hpp;include/euxis/etx/oauth_flow.hpp;include/euxis/etx/accessibility.hpp;src/main.cpp;src/app.cpp;src/theme.cpp;src/config.cpp;src/registry.cpp;src/screens/welcome.cpp;src/screens/dashboard.cpp;src/screens/agent.cpp;src/screens/about.cpp;src/screens/fleet_monitor.cpp;src/screens/settings.cpp;src/screens/help.cpp;src/screens/logs.cpp;src/screens/playbooks.cpp;src/screens/approvals.cpp;src/screens/cortex.cpp;src/screens/error_details.cpp;src/screens/metrics.cpp;src/screens/omnigraph.cpp;src/screens/squad_detail.cpp;src/screens/time_travel.cpp;src/screens/tool_runner.cpp;src/widgets/header.cpp;src/widgets/shortcut_bar.cpp;src/widgets/fleet_grid.cpp;src/widgets/agent_card.cpp;src/widgets/search_bar.cpp;src/widgets/tip_bar.cpp;src/widgets/output_panel.cpp;src/widgets/provider_select.cpp;src/widgets/resource_monitor.cpp;src/widgets/scroll_minimap.cpp;src/widgets/sparkline.cpp;src/accessibility.cpp;src/chat_engine.cpp;src/oauth_flow.cpp;src/widgets/conversation.cpp;src/widgets/chat_input.cpp;src/ghost_text.cpp;src/widgets/breadcrumb.cpp;src/widgets/bento_layout.cpp;src/widgets/collapsible_section.cpp;src/semantic_colors.cpp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/.qt/rcc/qrc_resources.cpp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/.qt/rcc/resources.qrc;/home/seb/.euxis/euxis-cpp/euxis-etx/resources/styles/liquid-glass.qss;/home/seb/.euxis/euxis-cpp/euxis-etx/resources/styles/calm.qss;/home/seb/.euxis/euxis-cpp/euxis-etx/resources/styles/focused.qss;/home/seb/.euxis/euxis-cpp/euxis-etx/resources/icons/euxis-logo.svg;/home/seb/.euxis/euxis-cpp/build-cov/.qt/rcc/euxis-etx_translations.qrc;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_en.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_fr.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_es.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_de.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_pt.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_zh.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_ja.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_ko.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_ru.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_it.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_ar.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_he.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_hi.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_nl.qm;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis_etx_id.qm;/home/seb/.euxis/euxis-cpp/build-cov/.qt/rcc/qrc_euxis-etx_translations.cpp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx_autogen/timestamp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/.qt/rcc/qrc_resources.cpp.rule;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx_autogen/timestamp.rule")
set(lupdate_subproject34_excluded "")
set(lupdate_subproject34_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx_autogen")

set(lupdate_subproject35_source_dir "/home/seb/.euxis/euxis-cpp/euxis-etx")
set(lupdate_subproject35_include_paths "/home/seb/.euxis/euxis-cpp/euxis-etx/include;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx-tests_autogen/include;/usr/include/qt6/QtWidgets;/usr/include/qt6;/usr/include/qt6/QtCore;/usr/include/qt6;/usr/lib/qt6/mkspecs/linux-g++;/usr/include/qt6;/usr/include/qt6/QtGui;/usr/include/qt6;/usr/include;/usr/include;/usr/include;/usr/include/qt6/QtNetwork;/usr/include/qt6;/usr/include/qt6/QtSvgWidgets;/usr/include/qt6;/usr/include/qt6/QtSvg;/usr/include/qt6;/usr/include/qt6/QtConcurrent;/usr/include/qt6;/usr/include/qt6/QtTest;/usr/include/qt6;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-cli-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-identity-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-inference-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-a2a-cpp/include;")
set(lupdate_subproject35_sources "/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx-tests_autogen/mocs_compilation.cpp;include/euxis/etx/app.hpp;include/euxis/etx/theme.hpp;include/euxis/etx/registry.hpp;include/euxis/etx/chat_engine.hpp;include/euxis/etx/conversation_widget.hpp;include/euxis/etx/chat_input_widget.hpp;include/euxis/etx/accessibility.hpp;include/euxis/etx/ghost_text.hpp;include/euxis/etx/breadcrumb_widget.hpp;include/euxis/etx/bento_layout.hpp;include/euxis/etx/collapsible_section.hpp;include/euxis/etx/semantic_colors.hpp;include/euxis/etx/oauth_flow.hpp;src/config.cpp;src/registry.cpp;src/theme.cpp;src/accessibility.cpp;src/ghost_text.cpp;src/semantic_colors.cpp;src/app.cpp;src/chat_engine.cpp;src/oauth_flow.cpp;src/screens/welcome.cpp;src/screens/dashboard.cpp;src/screens/agent.cpp;src/screens/about.cpp;src/screens/fleet_monitor.cpp;src/screens/settings.cpp;src/screens/help.cpp;src/screens/logs.cpp;src/screens/playbooks.cpp;src/screens/approvals.cpp;src/screens/cortex.cpp;src/screens/error_details.cpp;src/screens/metrics.cpp;src/screens/omnigraph.cpp;src/screens/squad_detail.cpp;src/screens/time_travel.cpp;src/screens/tool_runner.cpp;src/widgets/breadcrumb.cpp;src/widgets/bento_layout.cpp;src/widgets/collapsible_section.cpp;src/widgets/header.cpp;src/widgets/shortcut_bar.cpp;src/widgets/fleet_grid.cpp;src/widgets/agent_card.cpp;src/widgets/search_bar.cpp;src/widgets/tip_bar.cpp;src/widgets/output_panel.cpp;src/widgets/provider_select.cpp;src/widgets/resource_monitor.cpp;src/widgets/scroll_minimap.cpp;src/widgets/sparkline.cpp;src/widgets/conversation.cpp;src/widgets/chat_input.cpp;tests/etx_test_main.cpp;tests/test_config.cpp;tests/test_registry.cpp;tests/test_theme.cpp;tests/test_accessibility.cpp;tests/test_ghost_text.cpp;tests/test_breadcrumb.cpp;tests/test_bento_layout.cpp;tests/test_collapsible_section.cpp;tests/test_semantic_colors.cpp;tests/test_screens.cpp;tests/test_widgets.cpp;tests/test_chat_engine.cpp;tests/test_oauth_flow.cpp;tests/test_app.cpp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/.qt/rcc/qrc_test_resources.cpp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx-tests_autogen/timestamp;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/.qt/rcc/qrc_test_resources.cpp.rule;/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx-tests_autogen/timestamp.rule")
set(lupdate_subproject35_excluded "")
set(lupdate_subproject35_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/euxis-etx/euxis-etx-tests_autogen")

set(lupdate_subproject36_source_dir "/home/seb/.euxis/euxis-cpp/tests-integration")
set(lupdate_subproject36_include_paths "/home/seb/.euxis/euxis-cpp/euxis-crypto-cpp/include;;/usr/include;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-memory-cpp/include;;/usr/include;/usr/include;/home/seb/.euxis/euxis-cpp/euxis-bridge-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-core-cpp/include;;/home/seb/.euxis/euxis-cpp/euxis-metrics-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/ixwebsocket-src/;/home/seb/.euxis/euxis-cpp/euxis-cli-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-runtime-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-gateway-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-security-cpp/include;/home/seb/.euxis/euxis-cpp/euxis-adapters-cpp/include;/home/seb/.euxis/euxis-cpp/build-cov/_deps/httplib-src;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include")
set(lupdate_subproject36_sources "test_crypto_memory_roundtrip.cpp;test_bridge_admission_pipeline.cpp;test_metrics_collection_analysis.cpp;test_cli_dispatch_pipeline.cpp;test_core_resilience_swarm.cpp")
set(lupdate_subproject36_excluded "")
set(lupdate_subproject36_autogen_dir "/home/seb/.euxis/euxis-cpp/build-cov/tests-integration/euxis-integration-tests_autogen")
