// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2024-2026 Sebastien Rousseau · https://sebastienrousseau.com

#![warn(missing_docs)]

//! Example Euxis Wasm agent built with [`euxis_sdk`].
//!
//! This crate compiles to a `cdylib` Wasm module that the Euxis
//! runtime loads and invokes via Extism.
//!
//! # Invocation
//!
//! ```text
//! euxis-wasm my-agent.wasm '{"goal": "status"}'
//! ```

use serde::{Deserialize, Serialize};

/// Input payload deserialized from the host.
///
/// # Example
///
/// ```
/// let json = r#"{"goal":"status"}"#;
/// let input: my_euxis_agent::Input = serde_json::from_str(json).unwrap();
/// assert_eq!(input.goal, "status");
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Input {
    /// The agent's objective for this invocation.
    pub goal: String,
}

/// Output payload returned to the host.
///
/// # Example
///
/// ```
/// let output = my_euxis_agent::Output {
///     result: "done".into(),
///     metrics: None,
///     signature: None,
/// };
/// assert_eq!(output.result, "done");
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Output {
    /// Human-readable result summary.
    pub result: String,
    /// Optional runtime metrics snapshot.
    pub metrics: Option<serde_json::Value>,
    /// Optional cryptographic signature of [`result`](Self::result).
    pub signature: Option<String>,
}

/// Process an agent invocation from raw JSON input.
///
/// This contains the core agent logic, separated from the
/// `#[plugin_fn]` entry point for testability.
///
/// # Errors
///
/// Returns an error string if the input JSON is malformed.
pub fn process_input(
    raw: &str,
    metrics: Option<serde_json::Value>,
    mut signature_fn: impl FnMut(&str) -> Option<String>,
) -> Result<String, String> {
    let input: Input =
        serde_json::from_str(raw).map_err(|e| e.to_string())?;

    let result_text = format!("Agent processed goal: {}", input.goal);
    let signature = signature_fn(&result_text);

    let output = Output {
        result: result_text,
        metrics,
        signature,
    };

    serde_json::to_string(&output).map_err(|e| e.to_string())
}

/// Wasm plugin entry point (generated by `#[plugin_fn]`).
///
/// The `#[plugin_fn]` macro emits a `pub extern "C" fn` wrapper that
/// cannot carry doc attributes, so we isolate it in this module.
#[allow(missing_docs)]
mod entry {
    use super::*;
    use euxis_sdk::{get_metrics, sign_payload};
    use extism_pdk::*;

    /// Main entry point for the Euxis Wasm agent.
    ///
    /// Parses the [`Input`], fetches host metrics, signs the result via
    /// the Euxis cryptographic provenance system, and returns an [`Output`].
    ///
    /// Triggered by: `euxis-wasm my-agent.wasm '{"goal": "status"}'`
    ///
    /// # Errors
    ///
    /// Returns an Extism error if JSON parsing or output encoding fails.
    #[plugin_fn]
    pub fn run(input: String) -> FnResult<String> {
        let metrics = get_metrics().ok();
        let json = process_input(&input, metrics, |payload| {
            sign_payload(payload).ok()
        })
        .map_err(|e| extism_pdk::Error::msg(e))?;
        Ok(json)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // ── Input ────────────────────────────────────────────────────────

    #[test]
    fn input_deserialize() {
        let i: Input = serde_json::from_str(r#"{"goal":"status"}"#).unwrap();
        assert_eq!(i.goal, "status");
    }

    #[test]
    fn input_deserialize_empty_goal() {
        let i: Input = serde_json::from_str(r#"{"goal":""}"#).unwrap();
        assert_eq!(i.goal, "");
    }

    #[test]
    fn input_deserialize_unicode() {
        let i: Input =
            serde_json::from_str(r#"{"goal":"检查状态"}"#).unwrap();
        assert_eq!(i.goal, "检查状态");
    }

    #[test]
    fn input_deserialize_special_chars() {
        let i: Input =
            serde_json::from_str(r#"{"goal":"a \"quoted\" goal"}"#).unwrap();
        assert!(i.goal.contains("quoted"));
    }

    #[test]
    fn input_deserialize_missing_goal() {
        let r = serde_json::from_str::<Input>(r#"{}"#);
        assert!(r.is_err());
    }

    #[test]
    fn input_deserialize_wrong_type() {
        let r = serde_json::from_str::<Input>(r#"{"goal":42}"#);
        assert!(r.is_err());
    }

    #[test]
    fn input_deserialize_extra_fields() {
        let i: Input = serde_json::from_str(
            r#"{"goal":"test","extra":"ignored"}"#,
        )
        .unwrap();
        assert_eq!(i.goal, "test");
    }

    #[test]
    fn input_deserialize_invalid_json() {
        let r = serde_json::from_str::<Input>("not json");
        assert!(r.is_err());
    }

    #[test]
    fn input_serialize() {
        let i = Input {
            goal: "audit".into(),
        };
        let json = serde_json::to_string(&i).unwrap();
        assert!(json.contains("audit"));
        assert!(json.contains("goal"));
    }

    #[test]
    fn input_roundtrip() {
        let original = Input {
            goal: "deep review".into(),
        };
        let json = serde_json::to_string(&original).unwrap();
        let restored: Input = serde_json::from_str(&json).unwrap();
        assert_eq!(original, restored);
    }

    #[test]
    fn input_clone() {
        let a = Input {
            goal: "test".into(),
        };
        let b = a.clone();
        assert_eq!(a, b);
    }

    #[test]
    fn input_debug() {
        let i = Input {
            goal: "check".into(),
        };
        let dbg = format!("{:?}", i);
        assert!(dbg.contains("Input"));
        assert!(dbg.contains("check"));
    }

    #[test]
    fn input_partial_eq() {
        let a = Input { goal: "x".into() };
        let b = Input { goal: "x".into() };
        let c = Input { goal: "y".into() };
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    // ── Output ───────────────────────────────────────────────────────

    #[test]
    fn output_all_fields() {
        let o = Output {
            result: "done".into(),
            metrics: Some(json!({"count": 5})),
            signature: Some("sig123".into()),
        };
        assert_eq!(o.result, "done");
        assert_eq!(o.metrics.unwrap()["count"], 5);
        assert_eq!(o.signature.unwrap(), "sig123");
    }

    #[test]
    fn output_none_fields() {
        let o = Output {
            result: "done".into(),
            metrics: None,
            signature: None,
        };
        assert!(o.metrics.is_none());
        assert!(o.signature.is_none());
    }

    #[test]
    fn output_serialize_with_none() {
        let o = Output {
            result: "ok".into(),
            metrics: None,
            signature: None,
        };
        let json = serde_json::to_string(&o).unwrap();
        assert!(json.contains("null") || json.contains("result"));
    }

    #[test]
    fn output_serialize_with_some() {
        let o = Output {
            result: "ok".into(),
            metrics: Some(json!({"a": 1})),
            signature: Some("abc".into()),
        };
        let json = serde_json::to_string(&o).unwrap();
        assert!(json.contains("abc"));
    }

    #[test]
    fn output_deserialize() {
        let json = r#"{"result":"ok","metrics":null,"signature":null}"#;
        let o: Output = serde_json::from_str(json).unwrap();
        assert_eq!(o.result, "ok");
        assert!(o.metrics.is_none());
    }

    #[test]
    fn output_deserialize_with_values() {
        let json = r#"{"result":"done","metrics":{"x":1},"signature":"s"}"#;
        let o: Output = serde_json::from_str(json).unwrap();
        assert_eq!(o.result, "done");
        assert_eq!(o.metrics.unwrap()["x"], 1);
        assert_eq!(o.signature.unwrap(), "s");
    }

    #[test]
    fn output_roundtrip() {
        let original = Output {
            result: "test".into(),
            metrics: Some(json!({"latency": 42})),
            signature: Some("sig".into()),
        };
        let json = serde_json::to_string(&original).unwrap();
        let restored: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(original, restored);
    }

    #[test]
    fn output_roundtrip_none() {
        let original = Output {
            result: "test".into(),
            metrics: None,
            signature: None,
        };
        let json = serde_json::to_string(&original).unwrap();
        let restored: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(original, restored);
    }

    #[test]
    fn output_clone() {
        let a = Output {
            result: "r".into(),
            metrics: Some(json!(1)),
            signature: None,
        };
        let b = a.clone();
        assert_eq!(a, b);
    }

    #[test]
    fn output_debug() {
        let o = Output {
            result: "r".into(),
            metrics: None,
            signature: None,
        };
        let dbg = format!("{:?}", o);
        assert!(dbg.contains("Output"));
    }

    #[test]
    fn output_partial_eq() {
        let a = Output {
            result: "x".into(),
            metrics: None,
            signature: None,
        };
        let b = Output {
            result: "x".into(),
            metrics: None,
            signature: None,
        };
        let c = Output {
            result: "y".into(),
            metrics: None,
            signature: None,
        };
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn output_deserialize_missing_result() {
        let json = r#"{"metrics":null,"signature":null}"#;
        let r = serde_json::from_str::<Output>(json);
        assert!(r.is_err());
    }

    #[test]
    fn output_deserialize_extra_fields() {
        let json = r#"{"result":"ok","metrics":null,"signature":null,"extra":1}"#;
        let o: Output = serde_json::from_str(json).unwrap();
        assert_eq!(o.result, "ok");
    }

    // ── process_input ────────────────────────────────────────────────

    #[test]
    fn process_input_success_no_sign() {
        let json = process_input(
            r#"{"goal":"status"}"#,
            None,
            |_| None,
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(o.result, "Agent processed goal: status");
        assert!(o.metrics.is_none());
        assert!(o.signature.is_none());
    }

    #[test]
    fn process_input_success_with_metrics() {
        let metrics = Some(json!({"invocations": 10}));
        let json = process_input(
            r#"{"goal":"check"}"#,
            metrics,
            |_| None,
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(o.metrics.unwrap()["invocations"], 10);
    }

    #[test]
    fn process_input_success_with_signature() {
        let json = process_input(
            r#"{"goal":"audit"}"#,
            None,
            |payload| Some(format!("sig:{}", payload)),
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert!(o.signature.unwrap().starts_with("sig:Agent"));
    }

    #[test]
    fn process_input_success_with_all() {
        let json = process_input(
            r#"{"goal":"full"}"#,
            Some(json!({"ok": true})),
            |_| Some("signed".into()),
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(o.result, "Agent processed goal: full");
        assert!(o.metrics.is_some());
        assert_eq!(o.signature.unwrap(), "signed");
    }

    #[test]
    fn process_input_invalid_json() {
        let r = process_input("not json", None, |_| None);
        assert!(r.is_err());
    }

    #[test]
    fn process_input_missing_goal() {
        let r = process_input("{}", None, |_| None);
        assert!(r.is_err());
    }

    #[test]
    fn process_input_wrong_type() {
        let r = process_input(r#"{"goal":42}"#, None, |_| None);
        assert!(r.is_err());
    }

    #[test]
    fn process_input_empty_string() {
        let r = process_input("", None, |_| None);
        assert!(r.is_err());
    }

    #[test]
    fn process_input_empty_goal() {
        let json = process_input(
            r#"{"goal":""}"#,
            None,
            |_| None,
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(o.result, "Agent processed goal: ");
    }

    #[test]
    fn process_input_unicode_goal() {
        let json = process_input(
            r#"{"goal":"日本語"}"#,
            None,
            |_| None,
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert!(o.result.contains("日本語"));
    }

    #[test]
    fn process_input_long_goal() {
        let goal = "x".repeat(10_000);
        let input = format!(r#"{{"goal":"{}"}}"#, goal);
        let json = process_input(&input, None, |_| None).unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert!(o.result.len() > 10_000);
    }

    #[test]
    fn process_input_special_chars_goal() {
        let json = process_input(
            r#"{"goal":"a\"b\\c\nd"}"#,
            None,
            |_| None,
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert!(o.result.contains("a\"b\\c\nd"));
    }

    #[test]
    fn process_input_output_is_valid_json() {
        let json = process_input(
            r#"{"goal":"test"}"#,
            Some(json!({"a": [1, 2]})),
            |p| Some(p.to_uppercase()),
        )
        .unwrap();
        // Must parse as valid JSON
        let _: serde_json::Value = serde_json::from_str(&json).unwrap();
    }

    #[test]
    fn process_input_signature_receives_result_text() {
        let mut captured = String::new();
        let _ = process_input(
            r#"{"goal":"capture"}"#,
            None,
            |payload| {
                captured = payload.to_owned();
                None
            },
        );
        assert_eq!(captured, "Agent processed goal: capture");
    }

    #[test]
    fn process_input_extra_fields_ignored() {
        let json = process_input(
            r#"{"goal":"test","extra":"ignored"}"#,
            None,
            |_| None,
        )
        .unwrap();
        let o: Output = serde_json::from_str(&json).unwrap();
        assert_eq!(o.result, "Agent processed goal: test");
    }
}
