#!/bin/bash
set -euo pipefail

# Euxis Documentation Sync Script
# Generated by librarian agent for registry reconciliation and version verification

REGISTRY_FILE="/home/seb/.euxis/registry.json"
USER_GUIDE="/home/seb/.euxis/docs/user-guide.md"
README_FILE="/home/seb/.euxis/README.md"
FLEET_GUIDE="/home/seb/.euxis/docs/fleet-guide.md"

# Get system version from registry.json
SYSTEM_VERSION=$(jq -r '.protocol_version' "$REGISTRY_FILE")
echo "System version: $SYSTEM_VERSION"

# Verify version consistency across key documentation files
echo "Verifying version consistency..."

# Check README version
README_VERSION=$(head -10 "$README_FILE" | grep "Version" | head -1 | sed 's/.*Version //' | tr -d ' ')
if [[ "$README_VERSION" != "$SYSTEM_VERSION" ]]; then
    echo "WARNING: README version mismatch - found $README_VERSION, expected $SYSTEM_VERSION"
fi

# Check User Guide version
USER_GUIDE_VERSION=$(head -10 "$USER_GUIDE" | grep "Version" | head -1 | sed 's/.*Version //' | tr -d ' ')
if [[ "$USER_GUIDE_VERSION" != "$SYSTEM_VERSION" ]]; then
    echo "WARNING: User Guide version mismatch - found $USER_GUIDE_VERSION, expected $SYSTEM_VERSION"
fi

# Check Fleet Guide version
FLEET_GUIDE_VERSION=$(head -10 "$FLEET_GUIDE" | grep "Version" | head -1 | sed 's/.*Version //' | tr -d ' ')
if [[ "$FLEET_GUIDE_VERSION" != "$SYSTEM_VERSION" ]]; then
    echo "WARNING: Fleet Guide version mismatch - found $FLEET_GUIDE_VERSION, expected $SYSTEM_VERSION"
fi

# Extract agent counts from registry
TOTAL_AGENTS=$(jq '.agents | length' "$REGISTRY_FILE")
CORE_AGENTS=$(jq '.agents | map(select(.tier == "core")) | length' "$REGISTRY_FILE")
FLEET_AGENTS=$(jq '.agents | map(select(.tier == "fleet")) | length' "$REGISTRY_FILE")
DEFAULT_AGENTS=$(jq '.agents | map(select(.activation == "default" or (.activation | not))) | length' "$REGISTRY_FILE")
ONDEMAND_AGENTS=$(jq '.agents | map(select(.activation == "on-demand")) | length' "$REGISTRY_FILE")

echo "Registry stats: $TOTAL_AGENTS total ($CORE_AGENTS core, $FLEET_AGENTS fleet, $DEFAULT_AGENTS default, $ONDEMAND_AGENTS on-demand)"

# Generate agent roster for fleet guide
echo "Generating agent roster..."

# Core agents
echo "### Core agents:"
jq -r '.agents[] | select(.tier == "core") | "| `\(.id)` | \(.tags[0] // "core") |"' "$REGISTRY_FILE"

echo ""

# Default agents (fleet tier, not on-demand)
echo "### Default agents:"
jq -r '.agents[] | select(.tier == "fleet" and (.activation == "default" or (.activation | not))) | "| `\(.id)` | \(.tags[0] // "default") |"' "$REGISTRY_FILE"

echo ""

# On-demand agents
echo "### On-demand agents:"
jq -r '.agents[] | select(.activation == "on-demand") | "| `\(.id)` | \(.tags[0] // "on-demand") |"' "$REGISTRY_FILE"

# Verify all referenced agents exist in registry
echo ""
echo "Verifying agent references in documentation..."

# Get list of all valid agent IDs from registry
VALID_AGENTS=$(jq -r '.agents[].id' "$REGISTRY_FILE" | sort | tr '\n' ' ')

# Check for any agent references in docs that don't exist in registry
echo "Valid agent roster: $VALID_AGENTS"

# Generate updated fleet roster for USER_GUIDE
echo ""
echo "Fleet roster verification complete."
echo "Registry contains $TOTAL_AGENTS agents with consistent structure."
echo "Version $SYSTEM_VERSION verified across documentation files."
echo ""
echo "Documentation sync completed successfully."