# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# NOTE: Python package paths removed — the former euxis-core, euxis-cli,
# euxis-metrics, euxis-crypto, euxis-tui, euxis-gateway, euxis-adapters, and
# euxis-security Python packages have been replaced by C++23 modules under
# libs/ and apps/.  Documentation is now generated by DocuWriter.ai, not Sphinx
# autodoc.  This conf.py is retained only for legacy Sphinx/MkDocs compatibility.

# -- Project information -----------------------------------------------------

project = "Euxis"
copyright = f"{datetime.now().year}, Euxis Fleet"
author = "Euxis Fleet"
version = "0.0.2"
release = "v0.0.2"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.todo",
    "myst_parser",
]

# MyST parser settings (for Markdown support)
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "tasklist",
    "fieldlist",
    "attrs_inline",
]
myst_heading_anchors = 3
myst_highlight_code_blocks = False
myst_suppress_warnings = ["xref_missing"]

# Suppress warnings for missing cross-references in markdown
myst_url_schemes = ["http", "https", "mailto"]
suppress_warnings = [
    "myst.xref_missing",
    "toc.not_included",
    "autodoc.import_object",
    "autodoc",
]

# Source file suffixes
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master document
master_doc = "index"

# Patterns to exclude
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "**/.git",
    "mkdocs.yml",
    "**/README.md",
    "**/*.orig",
]

# Templates path
templates_path = ["_templates"]

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_title = "Euxis Documentation"
html_static_path = ["_static"]

# Theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# -- Options for autodoc -----------------------------------------------------

autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}

autodoc_typehints = "description"
autodoc_class_signature = "separated"

# Mock imports for modules that may not be available
autodoc_mock_imports = [
    "chromadb",
    "sentence_transformers",
    "textual",
    "rich",
    "httpx",
    "fastapi",
    "uvicorn",
    "slack_sdk",
    "telegram",
    "cryptography",
    "shared",
    "shared.crypto_bridge",
]

# -- Options for autosummary -------------------------------------------------

autosummary_generate = True

# -- Options for Napoleon (Google/NumPy docstrings) --------------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False

# -- Options for todo extension ----------------------------------------------

todo_include_todos = True
